package com.kofta.app.dispatchers;

import com.kofta.app.events.PodEvent;
import javax.mail.*;
import javax.mail.internet.*;
import java.util.Properties;
import java.time.format.DateTimeFormatter;

public class EmailAlertDispatcher implements AlertDispatcher<PodEvent> {

    private final String username;
    private final String toEmail;
    private final Session session;
    private static final DateTimeFormatter TIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    public EmailAlertDispatcher(String host, String port, String username, String password, String toEmail) {
        this.username = username;
        this.toEmail = toEmail;

        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", host);
        props.put("mail.smtp.port", port);

        this.session = Session.getInstance(props, new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });
    }

    @Override
    public void dispatch(PodEvent event) {
        if (!"Warning".equalsIgnoreCase(event.type())) {
            return;
        }

        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(username));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(toEmail));
            
            String eventName = event.getClass().getSimpleName();
            message.setSubject("K8S ALERT: " + eventName + " - " + event.context().namespace());

            String htmlContent = String.format(
                "<div style='font-family: Arial, sans-serif; border: 1px solid #333; border-radius: 4px; padding: 20px; max-width: 600px;'>" +
                "  <h2 style='color: #b91c1c; border-bottom: 2px solid #b91c1c; padding-bottom: 10px; margin-top: 0;'>System Alert Details</h2>" +
                "  <table style='width: 100%%; border-collapse: collapse; margin-top: 15px;'>" +
                "    <tr style='background-color: #f3f4f6;'><td style='padding: 10px; font-weight: bold; border: 1px solid #e5e7eb;'>Event</td><td style='padding: 10px; border: 1px solid #e5e7eb;'>%s</td></tr>" +
                "    <tr><td style='padding: 10px; font-weight: bold; border: 1px solid #e5e7eb;'>Resource</td><td style='padding: 10px; border: 1px solid #e5e7eb;'>%s</td></tr>" +
                "    <tr style='background-color: #f3f4f6;'><td style='padding: 10px; font-weight: bold; border: 1px solid #e5e7eb;'>Namespace</td><td style='padding: 10px; border: 1px solid #e5e7eb;'>%s</td></tr>" +
                "    <tr><td style='padding: 10px; font-weight: bold; border: 1px solid #e5e7eb;'>Timestamp</td><td style='padding: 10px; border: 1px solid #e5e7eb;'>%s</td></tr>" +
                "    <tr style='background-color: #fef2f2;'><td style='padding: 10px; font-weight: bold; border: 1px solid #e5e7eb;'>Description</td><td style='padding: 10px; border: 1px solid #e5e7eb; color: #b91c1c;'>%s</td></tr>" +
                "  </table>" +
                "  <div style='margin-top: 20px; font-size: 11px; color: #6b7280; text-align: center; border-top: 1px solid #eee; padding-top: 10px;'>" +
                "    Generated by Automated Monitoring System" +
                "  </div>" +
                "</div>",
                eventName,
                event.context().name(),
                event.context().namespace(),
                event.timestamp().format(TIME_FORMATTER),
                event.rawMessage()
            );

            message.setContent(htmlContent, "text/html; charset=utf-8");
            Transport.send(message);

            System.out.println("[DISPATCH] Email alert dispatched to: " + toEmail);

        } catch (MessagingException e) {
            System.err.println("[ERROR] Failed to dispatch email: " + e.getMessage());
        }
    }
}