# Default values for j-kube-watch.

replicaCount: 1

image:
  repository: kofta/j-kube-watch
  pullPolicy: Never
  tag: "latest"

serviceAccount:
  name: "j-kube-watch-sa"

rbac:
  create: true
  roleName: "j-kube-watch-role"
  bindingName: "j-kube-watch-binding"