apiVersion: apps/v1
kind: Deployment
metadata:
  name: creative-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: creative-operator
  template:
    metadata:
      labels:
        app: creative-operator
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}